version: '1'

###############################################################################
#DOCKER-COMPOSE 
###############################################################################
# Docker-compose creates a network that. All the other docker images join this networ, forming a cluster #########
# Network name will same as the parent direcotry name #########
############################################################################
 
#---------------------------------------
# MASTER CONFIGURATION 
#---------------------------------------
 
services:
  master:
    build: .
    image: pavanpkulkarni/spark_image_2.0.1:first_image
    container_name: master
    ports:
      - "8080:8080"
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]
#---------------------------------------
# SLAVE CONFIGURATION 
#---------------------------------------
  slave:
    image: pavanpkulkarni/spark_image_2.0.1:first_image
    depends_on:
      - master
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]
